### ISSUE TITLE
Not loading bookmarks.data - Console error

### ISSUE THREAD

**Issue by casman300** [skx/bookmarks.public#23]
When trying to load the page am getting an error as below. 

![errpr](https://cloud.githubusercontent.com/assets/2879023/20869589/68e050f6-ba6d-11e6-818e-c6b82dd6f4f7.PNG)

```
XMLHttpRequest cannot load file:///T:/Web-Dev/Github/bookmarks.public/bookmarks.data. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery-3.0.0.min.js:4
```

Thought this may be related to storing everything from Github on an external drive but get the same error when copying everything to the C:\\ drive and trying to run it there.

From the index file looks like this is what the script is trying to prevent? Could this be a windows 10 only issue? Am also using Google Chrome.

Will update issue as I find anything else useful.

**Comment by casman300** [comment]
Hum, Works fine in Firefox so may be security settings related.

**Comment by skx** [comment]
Yeah this is a security thing; most browsers don't allow you to open a HTML file and use AJAX to load other files locally - because it's a risk if you allow javascript to read a local file and then POST it somewhere else.

I've tried to be careful such that this _does_ work, but really the ideal is to store your bookmarks on a remote webserver - github pages will do - such that you're fetching the CSS, JS, and data via normal HTTP.  That'll work everywhere and allow your bookmarks to be portable too.

**Comment by casman300** [comment]
Thanks for you help, am now accessing this through a local web server and is working fine.
Will have a look at getting this to connect to a database when I have more time to make it easier to save new bookmarks.
