### ISSUE TITLE
Add an other view [enhancement]

### ISSUE THREAD

**Issue by kafran** [skx/bookmarks.public#34]
Please, add an other view to list the bookmarks by tag or category, something like this: https://www.bucmarks.com/demo/

Thank you. This is a really useful program for whom is concerned about privacy.

**Comment by skx** [comment]
If somebody were to contribute an alternative layout, as an option, and the code were clean I would accept it, but I will almost certainly not write such a thing myself.

I know that having all the bookmarks be "flat", rather than "nested", might make it less useful for others, but it is good enough for my current use as-is.
